//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFenipo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPeso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaPeso()
        {
            this.InscripcionAtletas = new HashSet<InscripcionAtletas>();
        }
    
        public int Id { get; set; }
        public int NombreCategoriaPeso { get; set; }
        public string Genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionAtletas> InscripcionAtletas { get; set; }
    }
}
