//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFenipo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionAtletas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InscripcionAtletas()
        {
            this.Intento = new HashSet<Intento>();
        }
    
        public int Id { get; set; }
        public int AtletaId { get; set; }
        public int InscripcionEquipoId { get; set; }
        public int CompetenciaId { get; set; }
        public int CategoriaEdadId { get; set; }
        public int CategoriaPesoId { get; set; }
        public double PesoCorporal { get; set; }
        public double Total { get; set; }
        public double GLPoint { get; set; }
    
        public virtual Atleta Atleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intento> Intento { get; set; }
        public virtual InscripcionEquipo InscripcionEquipo { get; set; }
        public virtual Competencia Competencia { get; set; }
        public virtual CategoriaEdad CategoriaEdad { get; set; }
        public virtual CategoriaPeso CategoriaPeso { get; set; }
    }
}
