//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFenipo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intento
    {
        public int Id { get; set; }
        public int InscripcionAtletasId { get; set; }
        public decimal KilosMovimiento { get; set; }
        public int MovimientoId { get; set; }
        public int NumeroIntentoId { get; set; }
        public int StatusMovimientoId { get; set; }
    
        public virtual InscripcionAtletas InscripcionAtletas { get; set; }
        public virtual Movimiento Movimiento1 { get; set; }
        public virtual NumeroIntento NumeroIntento1 { get; set; }
        public virtual StatusMovimiento StatusMovimiento { get; set; }
    }
}
